apiVersion: v1
kind: PersistentVolume
metadata:
  name: abc-technologies-pv
  namespace: abc-technologies
  spec:
    capacity:
      storage: 1Gi
      accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: /mnt/data/java-webapp #create this path on host